<?
   print'<fieldset><legend><table border><tr><td><b><i>WYBOR POSTACI - OPIS SZCZEGOLOWY</i></b></td></tr></table></legend>';
   print'<p align="justify">Kazdy gracz ma prawo wybrac kim chce zagrac. Jedynym ograniczeniem jest sklad druzyny awanturnikow, a wiec postacie innych graczy. Grajacy w jednej grupie w praktyce nie powinni miec przeciwnych charakterow. Dobrze tez, aby wsrod nich znalazla sie co najmniej jedna osoba walczaca, jeden przedstawiciel klerykow, jeden czarodziej i ktos reprezentujacy kaste zlodziei (itp). Gracze moga wybrac sposrod 9 ras, 20 profesji (a wiec jakby "zawodow", ktore mozna by wykonywac i niekiedy laczyc) oraz 10 glownych i kilkunastu mniej istotnych wspolczynnikow okreslajacych cechy wybranej postaci (Awanturnika).';
   print'<fieldset><legend><table border><tr><td><b><i>***1***</i></b></td></tr></table></legend>';
   print'<p align="justify">Na poczatku gracz wybiera sobie rase, ktora chcialby reprezentowac. Moze wybierac wsrod nastepujacych:';
   print'<fieldset><UL>';
   print'<LI> LUDZIE - nadaje sie dobrze na kazda profesje i zapewnia minimum srednie wspolczynniki; ulubiona rasa kasty rycerskiej.';
   print'<LI> POLELFY - dobra rasa na postacie myslace i "wszedobylskie".';
   print'<LI> ELFY - wysmienita rasa dla czarodziejow i dla lekkozbrojnych.';
   print'<LI> POLORKI - dobra rasa dla postaci walczacych i zlodziei.';
   print'<LI> POLOLBRZYMY - rasa wielkich silaczy, za to kiepsko nadajaca sie dla postaci myslacych.';
   print'<LI> KRASNOLUDY - swietna rasa dla zolnierzy i klerykow.';
   print'<LI> GNOMY - najlepsza rasa dla klerykow i dobra dla czarodziejow.';
   print'<LI> HOBBICI - swietna rasa zlodziejska.';
   print'<LI> REPTILLIONI - wysmienita rasa dla rycerzy, wojownikow i wedlug niektorych dla czarodziejow.';
   print'</UL></fieldset></p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>***2***</i></b></td></tr></table></legend>';
   print'<p align="justify">Nastepnie ustalamy profesje, jaka bedzie spelnial nasz bohater.</p>';
   print'<p align="justify">Poprzez profesje nalezy rozumiec cos na ksztalt obranej kariery, pozwalajacej specjalizowac sie w okreslonym fachu. W grze tej zastalo opracowane 20 takich profesji, przy czym ze wzgledu na podobienstwa pogrupowano je w pewne grupy, zwane tu kastami. Istnieje tez mozliwosc grania postacia, ktora posiada zdolnosci dwoch nie wykluczajacych sie nawzajem profesji, jednakze ze wzgledu na potrzebna duza wiedze o ich zdolnosciach zalecamy to tylko doswiadczonym graczom.</p>';
   print'<p align="justify">Najbardziej znana kasta jest kasta zolnierska, do ktorej naleza nastepujace Funkcje:</p>';
   print'<fieldset><legend><table border><tr><td><b><i>Kasta Zolnierska</i></b></td></tr></table></legend>';
   print'<p align="justify"><UL>';
   print'<LI> WOJOWNIK - Jest to postac, ktora swietnie walczy i zmagania orezne stanowia dla niej istote zycia. W walce duzo potrafi, jednakze wiele ryzykuje.';
   print'<LI> LOWCA - Zajmuje sie najczesciej polowaniami, walka z dzikimi zwierzetami i uwielbia obcowac z przyroda. Jego mankamentem jest to, ze zawsze chce byc blisko przyrody i czesto ja chroni.';
   print'<LI> GWARDZISTA - Czesciowo "ubezwlasnowolniony", jako typowy platny najemnik, jednakze swietnie wyszkolony i bardzo niebezpieczny w walce.';
   print'<LI> BARBARZYÑCA - Prymitywny osilek, jednakze w trudnych sytuacjach niezastapiony i nieugiety. Jest niechetny magii i dobrze umie sie przed nia bronic.';
   print'<LI> WIEDZMIN - Inaczej nazywany rowniez lowca bestii wszelakich.</UL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Kasta Rycerska</i></b></td></tr></table></legend>';
   print'<p align="justify"><UL>';
   print'<LI> RYCERZ - Powolny, ale dzieki poteznej zbroi prawie niezniszczalny i swietnie wyszkolony w walce, szczegolnie z potworami. Dziala zawsze zgodnie z panujacym prawem, ale tam, gdzie go nie ma czesto sam lubi je stanowic.';
   print'<LI> PALADYN - Rycerz bez skazy, grozny dla wszystkiego co zle. Urodzony przywodca. Posiada tez troche mocy kaplanskiej i uzdrowicielskiej.';
   print'<LI> CZARNY RYCERZ - Odwrotnosc paladyna. Rycerz siejacy smierc i zniszczenie wsrod dobrych istot. Z czasem poznaje tez tajniki czarnej magii.</UL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Kasta Zlodziejska</i></b></td></tr></table></legend>';
   print'<p align="justify"><UL>';
   print'<LI> ZLODZIEJ - Mistrz bogacenia sie kosztem innych. Kazde drzwi stoja przed nim otworem. Wszedobylski, ale unika walki.';
   print'<LI> ZABOJCA - Niezwykle niebezpieczny specjalista od cichego eliminowania wrogow. Mimo, ze swietnie wyszkolony w walce, unika jej w otwartym starciu.';
   print'<LI> KUPIEC - W walce slaby, ale sila pieniadza i slowa w jego ustach potrafia wiecej niz niejeden orez lub czar. Latwo bogaci sie cudzym kosztem.';
   print'<LI> BARD - To postac rozmilowana w muzyce i we wspomnieniach.</UL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Kasta Klerykow (potrafia rzucac czary)</i></b></td></tr></table></legend>';
   print'<p align="justify"><UL>';
   print'<LI> KAPLAN - Gorliwy oredownik swego bostwa. Niezastapiony w grupie jako ten, ktory magia chroni i leczy innych. Ma duzy wplyw na "istoty martwe" i w wyrazny sposob zle lub dobre.';
   print'<LI> DRUID - Opiekun natury i jej pasterz. Jego magia potrafi wladac zwierzetami, pogoda i zywiolami.';
   print'<LI> ASTROLOG - Niezrownany badacz wszelkich tajemnic, magii i przeznaczenia. Jego magia wywiera ogromny wplyw na na istoty "nie z tego swiata".';
   print'<LI> POLBOG - To ten, ktory ustanawia wlasna wiare. Posiada potezna magie dzialajaca na wszystko. Potrafi takze korzystac z mocy innych bostw, jednak jest o tyle niebezpieczne, ze przy zauwazeniu przez jakiegos Boga moze go spotkac odpowiednia kara, a najmniejsza z nich jest smierc.</UL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Kasta Czarodziejow (potrafia rzucac czary)</i></b></td></tr></table></legend>';
   print'<p align="justify"><UL>';
   print'<LI> MAG - Perfekcyjnie zna sie na magii we wszelkich jej odmianach. Jego czary potrafia wszystko po trochu. Dysponuje silna magia bojowa i ochronna.';
   print'<LI> CZARNOKSIEZNIK - Wlada czarna magia i jej odmianami. Jego czary najczesciej wywoluja smierc i przerazenie. Przewaznie tepiony przez istoty o dobrych charakterach.';
   print'<LI> ILUZJONISTA - Jego magia jest w stanie zapanowac nad kazdym umyslem. Z czasem uwielbia otaczac sie uzaleznionymi od siebie, jednakze jest bezbronny w przypadku starcia z martwiakami.';
   print'<LI> ALCHEMIK - Jego mikstury z zabitych magicznych istot moga wszystko. Magia sluzy mu glownie do analizy, jednakze niepozbawiony jest czarow budzacych groze lub podziw.</UL></fieldset>';
   print'<p align="justify">Po dokonaniu wyboru profesji, proponujemy zapoznac sie z jej etosem, zwyczajami i zdolnosciami, znajdujacymi sie w KARCIE POSTACI: SZCZEGOLOWY OPIS.</p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>***3***</i></b></td></tr></table></legend>';
   print'<p align="justify">Teraz przychodzi kolej na okreslanie cech postaci, czyli tzw. wspolczynnikow. Podstawowe z nich okreslaja 10 najbardziej znaczacych dla postaci cech. Sa to:<fieldset><DL>';
   print'<DT> ZYWOTNOSC <DD> Decyduje o zmeczeniu i ilosci ran, jaka moze otrzymac postac nim umrze (ustala sie ja w zaleznosci od rasy, profesji i wagi).';
   print'<DT> SILA FIZYCZNA <DD> Decyduje, ile mozna podniesc, nosic i ile ran zadaje przeciwnikowi (ustala sie ja w zaleznosci od rasy, profesji, wagi i wrodzonych predyspozycji).';
   print'<DT> ZRECZNOSC <DD> Decyduje o sprawnosci w unikach, manipulacji, utrzymaniu rownowagi, itp. (ustala sie ja w zaleznosci od rasy, profesji, wagi i wrodzonych predyspozycji).';
   print'<DT> SZYBKOSC <DD> Decyduje o refleksie, mozliwosciach zaskoczenia przez przeciwnika, szybkosci poruszania sie, itp. (ustala sie ja w zaleznosci od rasy, profesji, wagi i wrodzonych predyspozycji).';
   print'<DT> INTELIGENCJA <DD> Okresla umiejetnosc rozwiazywania problemow, intuicje, bystrosc umyslu, itp. (ustala sie ja w zaleznosci od rasy, profesji i wrodzonych predyspozycji).';
   print'<DT> MADROSC <DD> Decyduje o zdolnosci zapamietywania i przypominania sobie wiadomosci, oraz o wiedzy postaci (ustala sie ja w zaleznosci od rasy, profesji i wrodzonych predyspozycji).';
   print'<DT> UMIEJETNOSCI MAGICZNE <DD> Okresla mozliwosci poslugiwania sie magia, jej rozumienie i postrzeganie (ustala sie je w zaleznosci od rasy, profesji i wrodzonych predyspozycji).';
   print'<DT> CHARYZMA <DD> Okresla wladczosc, ton i dostojenstwo glosu, sposob wyslawiania sie, elokwencje (ustala sie ja w zaleznosci od rasy, profesji, pochodzenia spo³ecznego i wrodzonych predyspozycji).';
   print'<DT> PREZENCJA <DD> Okresla urode, decyduje o wrazeniu przy pierwszym zetknieciu sie z dana postacia, milosci, itp. (ustala sie ja w zaleznosci od rasy, profesji, ubioru i wrodzonych predyspozycji).';
   print'<DT> WIARA <DD> Okresla oddanie sie jakiemus bostwu i umiejetnosc odprawiania prawidlowych modlow, itp. (ustala sie ja w zaleznosci od rasy, profesji i wrodzonych predyspozycji).</DL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Wspolczynniki Pomocnicze</i></b></td></tr></table></legend>';
   print'<p align="justify"><DL>';
   print'<DT> Bieglosc w uzyciu broni (wybranej z dostepnych dla postaci): <DD> Okresla procent wykorzystania skutecznosci raniacej broni i podstawowa szanse trafienia w przeciwnika. (Ustala sie ja w zaleznosci od rasy, profesji, wrodzonych i wyuczonych predyspozycji).';
   print'<DT> Trafienie w broni (w tej w ktorej ma sie juz bieglosc): <DD> Okresla rzeczywista szanse zranienia slabo broniacego sie przeciwnika (ustala sie ja w zaleznosci od posiadanej bieglosci oraz premii rownej 1/10 czesci Sily Fizycznej i Zrecznosci).';
   print'<DT> Maksymalna ilosc zadawanych ran (w wypadku skutecznego trafienia): <DD> Podczas zranienia, informuje o maksymalnej ilosci ran, ktora jest sie w stanie zadac dana bronia (ustala sie je w zaleznosci od wykorzystania raniacej skutecznosci broni, jak i premii do ran przyznawanej z Sily Fizycznej [dodaje sie 1/4 czesc SF jako rany]).';
   print'<b>Uwaga</b>: Ilosc ran modyfikowana jest o noszone zbroje, pancerze, wlasna gruba skore, magie, itp.';
   print'<DT> Obrona (w normalnych warunkach): <DD> Informuje o ile trudniej (lub latwiej) trafic jest przeciwnikowi, czyli okresla stopien mozliwosci unikniecia zranienia przez atakowanego (zalezy od posiadanej zrecznosci, magii ochronnej, zbroi, tarczy, a wypadku walki takze od premii obronnej broni).';
   print'<DT> Wyparowania <DD> Informuja ile ran z zadanego ciosu potrafi zatrzymac zbroja, skora lub magia np. dzieki grubosci, twardosci lub jakosci pancerza, czy odpowiedniej mocy czaru ochronnego.';
   print'<DT> Podstawowa Odpornosc na czynniki Psychiczne: <DD> Czyli tzw. BAZOWA PSYCHICZN0-FIZYCZNA - okresla podstawowa odpornosc organizmu na wszystko, co oddzialuje na umysl postaci, ew. na cialo (w jej sklad wchodzi 1/10 czesc Inteligencji, 1/10 czesc Madrosci i 1/20 czesc Zywotnosci). Baz.Psych.-Fiz. decyduje o:<fieldset><UL>';
   print'<LI> 1. Odpornosc na iluzje - (bazowa + modyfikacje wynikajace z rasy, profesji i inteligencji)';
   print'<LI> 2. Odpornosc na sugestie - (bazowa + modyfikacje wynikajace z rasy, profesji i madrosci)';
   print'<LI> 3. Odpornosc na zaklecia - (bazowa + modyfikacje wynikajace z rasy, profesji i wiary)';
   print'<LI> 4. Odpornosc na szok - (bazowa + modyfikacje wynikajace z rasy i profesji)';
   print'<LI> 5. Odpornosc na energie - (bazowa + modyfikacje wynikajace z rasy i profesji)</UL></fieldset>';
   print'<DT> Podstawowa odpornosc na czynniki Fizyczne: <DD> Czyli tzw. BAZOWA FIZYCZNO-PSYCHICZNA - okresla podstawowa odpornosc organizmu na wszystko, co oddzialuje na cialo postaci (w sklad jej wchodzi 1/10 czesc Zywotnosci i 1/10 czesc Sily Fizycznej). Bazowa ta decyduje o:<fieldset><UL>';
   print'<LI> 6. Odpornosc na trucizny - (bazowa + modyfikacje wynikajace z rasy i profesji)';
   print'<LI> 7. Odpornosc na gazy - (bazowa + modyfikacje wynikajace z rasy i profesji, ew. ze zbroi)';
   print'<LI> 8. Odpornosc na temperatury - (bazowa + modyfikacje wynikajace z rasy, profesji i ze zbroi)';
   print'<LI> 9. Odpornosc na elektrycznosc - (bazowa + modyfikacje wynikajace z rasy, profesji i ze zbroi)';
   print'<LI>10. Odpornosc na polimorfie - (bazowa + modyfikacje wynikajace z rasy, profesji i ze zbroi)</UL></fieldset></DL></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>Inne Wspolczynniki Dodatkowe</i></b></td></tr></table></legend>';
   print'<p align="justify"><DL>';
   print'<DT> Status spoleczny <DD> Okresla w jak wplywowej i zamoznej rodzinie urodzila sie dana postac (w zaleznosci, czy wylosowalo sie elite wladzy, arystokracje, mieszczanstwo, czy chlopstwo odpowiednio rozlosowuje sie majatek,ktorym mozna dysponowac rozpoczynajac gre).';
   print'<DT> Wzrost <DD> Zbyt maly wzrost niekiedy nie pozwala uzywac niektorych broni.';
   print'<DT> Waga <DD> Zbyt duza lub zbyt mala waga modyfikuje takie wspolczynniki jak Zywotnosc, Sila Fizyczna, Zrecznoœæ i Szybkosc.';
   print'<DT> Wiek <DD> Okresla aktualna ilosc lat, z jaka wkracza sie do gry po ukonczeniu szkolenia na dana profesje, w momencie gdy zaistnieje pierwsza szansa dolaczenia do grupy Awanturnikow lub samemu utworzenia takowej (zalezy od wieku dojrzewania rasy, dlugosci szkolenia i wyuczonych zawodow).';
   print'</DL></p></fieldset></fieldset></fieldset>';
?>


