<?
  $wynik=mysql_query("UPDATE istoty SET charakter1='".$_GET['charakter1']."',charakter2='".$_GET['charakter2']."' WHERE user='".$_GET['user']."';");
  $rekord=mysql_fetch_assoc(mysql_query("SELECT*FROM istoty WHERE user='".$_GET['user']."';"));
  $imie=$_GET['user'];
  $wynik1=mysql_query("SELECT*FROM bogowie;")or die("niemozna polaczyc z baza profesje");
  print("<FIELDSET><LEGEND><TABLE BORDER><TR><TD><B><I>WYBIERZ BOGA</I></B></TD></TR></TABLE></LEGEND><TABLE CELLPADING=5 BORDER=1>");
  while($rekord=mysql_fetch_assoc($wynik1)){

if($rekord['nazwa']=="DAGONIN BIALY"&&($postac['profesja1']=="Barbarzynca"||$postac['profesja2']=="Barbarzynca")){print("");}
elseif($rekord['nazwa']=="ASTERIUSZ WIELKI"&&(($postac['charakter1']=="Praworzadny"&&$postac['charakter2']=="Zly")&&($postac['charakter1']=="Neutralny"&&$postac['charakter2']=="Zly")&&($postac['charakter1']!="Chaotyczny"&&$postac['charakter2']!="Dobry"))||$postac['profesja1']=="Czarny Rycerz"||$postac['profesja2']=="Czarny Rycerz"){print("");}
elseif($rekord['nazwa']=="REPTILLION WIELKI"&&(($postac['charakter1']=="Chaotyczny"||$postac['profesja1']=="Barbarzynca"||$postac['profesja2']=="Barbarzynca"||$postac['profesja1']=="Zlodziej"||$postac['profesja2']=="Zlodziej"))){print("");}
elseif($rekord['nazwa']=="ORIAK"&&(($postac['charakter1']=="Chaotyczny"||$postac['profesja1']=="Lowca"||$postac['profesja2']=="Lowca"||$postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Barbarzynca"||$postac['profesja2']=="Barbarzynca"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"||$postac['profesja1']=="Pol Bog"))){print("");}
elseif($rekord['nazwa']=="KATAN"&&(($postac['rasa']!="Czlowiek"||$postac['rasa']!="Pol Elf"||$postac['rasa']!="Pol Ork"||$postac['rasa']!="Pol Olbrzym")||$postac['charakter1']=="Chaotyczny"||($postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Barbarzynca"||$postac['profesja2']=="Barbarzynca"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Zlodziej"||$postac['profesja2']=="Zlodziej"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"||$postac['profesja1']=="Pol Bog"||$postac['profesja1']=="Alchemik"||$postac['profesja2']=="Alchemik"))){print("");}
elseif($rekord['nazwa']=="SET"&&($postac['charakter2']=="Dobry"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn")){print("");}
elseif($rekord['nazwa']=="ARIANNA"&&(($postac['rasa']!="Czlowiek"||$postac['rasa']!="Pol Elf"||$postac['rasa']!="Elf"||$postac['rasa']!="Hobbit")||$postac['charakter1']=="Zly"||($postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Barbarzynca"||$postac['profesja2']=="Barbarzynca"||$postac['profesja1']=="Rycerz"||$postac['profesja2']=="Rycerz"||$postac['profesja1']=="Czarny Rycerz"||$postac['profesja2']=="Czarny Rycerz"||$postac['profesja1']=="Zabojca"||$postac['profesja2']=="Zabojca"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Pol Bog"||$postac['profesja1']=="Czarnoksieznik"||$postac['profesja2']=="Czarnoksieznik"))){print("");}
elseif($rekord['nazwa']=="SHARAMI"&&(($postac['rasa']!="Czlowiek"||$postac['rasa']!="Pol Elf"||$postac['rasa']!="Pol Ork"||$postac['rasa']!="Elf")||$postac['charakter1']=="Praworzadny"||($postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Rycerz"||$postac['profesja2']=="Rycerz"||$postac['profesja1']=="Czarny Rycerz"||$postac['profesja2']=="Czarny Rycerz"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Pol Bog"||$postac['profesja1']=="Iluzjonista"||$postac['profesja2']=="Iluzjonista"||$postac['profesja1']=="Czarnoksieznik"||$postac['profesja2']=="Czarnoksieznik"))){print("");}
elseif($rekord['nazwa']=="GOTAM-GOR"&&(($postac['rasa']!="Czlowiek"||$postac['rasa']!="Pol Olbrzym"||$postac['rasa']!="Pol Ork"||$postac['rasa']!="Krasnolud"||$postac['rasa']!="Gnom"||$postac['rasa']!="Reptylion")||($postac['profesja1']=="Zabojca"||$postac['profesja2']=="Zabojca"||$postac['profesja1']=="Iluzjonista"||$postac['profesja2']=="Iluzjonista"||$postac['profesja1']=="Czarnoksieznik"||$postac['profesja2']=="Czarnoksieznik"))){print("");}
elseif($rekord['nazwa']=="BELL"&&($postac['charakter1']=="Praworzadny"||($postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Gwardzista"||$postac['profesja2']=="Gwardzista"||$postac['profesja1']=="Rycerz"||$postac['profesja2']=="Rycerz"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Czarny Rycerz"||$postac['profesja2']=="Czarny Rycerz"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Pol Bog"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"||$postac['profesja1']=="Astrolog"||$postac['profesja2']=="Astrolog"))){print("");}
elseif($rekord['nazwa']=="PIAN"&&($postac['charakter1']=="Praworzadny"||($postac['profesja1']=="Wiedzmin"||$postac['profesja1']=="Gwardzista"||$postac['profesja2']=="Gwardzista"||$postac['profesja1']=="Rycerz"||$postac['profesja2']=="Rycerz"||$postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Czarny Rycerz"||$postac['profesja2']=="Czarny Rycerz"||$postac['profesja1']=="Bard"||$postac['profesja2']=="Bard"||$postac['profesja1']=="Pol Bog"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"||$postac['profesja1']=="Astrolog"||$postac['profesja2']=="Astrolog"))){print("");}
elseif($rekord['nazwa']=="GOTHMED"&&$postac['rasa']!="Hobbit"){print("");}
elseif($rekord['nazwa']=="HASAR-GRUN"&&(($postac['rasa']!="Czlowiek"||$postac['rasa']!="Pol Elf"||$postac['rasa']!="Pol Ork"||$postac['rasa']!="Krasnolud")||$postac['charakter2']=="Dobry"||($postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"))){print("");}
elseif($rekord['nazwa']=="NATA-KRANTA"&&(($postac['rasa']!="Reptylion"||$postac['rasa']!="Krasnolud")||($postac['charakter1']=="Praworzadny"&&$postac['charakter2']!="Zly")||($postac['charakter1']=="Neutralny"&&$postac['charakter2']!="Zly")||($postac['charakter1']=="Chaotyczny"&&$postac['charakter2']=="Dobry")||($postac['profesja1']=="Paladyn"||$postac['profesja2']=="Paladyn"||$postac['profesja1']=="Druid"||$postac['profesja2']=="Druid"||$postac['profesja1']=="Kupiec"||$postac['profesja2']=="Kupiec"))){print("");}



else{print("<TR><TD><A HREF=\"index.php?user=".$imie."&co=karta_postaci&haslo=".$_GET['haslo']."&bog=".$rekord['nazwa']."\">WYBIERZ</A></TD>");
print("<TD><CENTER><IMG SRC=".$rekord['symbol']."></CENTER></TD><TD><FIELDSET><LEGEND><TABLE BORDER><TR><TD><B><I>".$rekord['nazwa']."</I></B></TD></TR></TABLE></LEGEND><P ALIGN=justify><B>MIESIAC : </B>".$rekord['miesiac']."<BR><B>CHARAKTER : </B>".$rekord['charakter1']." - ".$rekord['charakter2']."<BR><BR><B>INFO : </B>".$rekord['info']."<BR><BR><B>ULUBIONA OFIARA : </B>".$rekord['ulubiona_ofiara']."<BR><BR><B>MIEJSCA KULTU :</B><BR>".$rekord['miejsca_kultu']."</P></td></tr>");};};

?>


