<?
   print'<fieldset><legend><table border><tr><td><b><i>WSTEP</i></b></td></tr></table></legend>';
   print'<p align="justify">Gra, ktora tu prezentuje, nalezy do gatunku gier RPG, w ktorych gracz wciela siê w wybrana przez siebie postac, decyduje czym sie ma ona zajmowac (wybiera jej profesje) oraz losuje jej wspolczynniki. Po dokonaniu wyboru, gracz prowadzi ja przez pelen tajemnic, potworow, skarbow i czego jeszcze dusza zapragnie - swiat fantasy, w ktorym mozesz dokonywac czynow szlachetnych lub podlych (zaleznie od wybranego charakteru) i tworzyc swoje drugie zycie.</p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>OPIS SWIATA</i></b></td></tr></table></legend>';
   print'<p align="justify"><img align="left" src="obrazy/img001.jpg" />Swiat w ktorym urodzil sie wasz bohater nazywa sie w prawie wszystkich znanych tam jezykach O R C H I A. Jest to bardo stary, magiczny swiat. Obok mitycznych potworow i wielu humanoidalnych ras mozna tez znalezc niezmiernie czesto ruiny i inne resztki poteznych lub malenkich, dawno wymarlych, niezliczonych starozytnych cywilizacji. W wyniku dzialania ogromnych sil, mocy, czy bostw, glob czesto bardzo sie zmienial. W chwili, w ktorej wam to przedstawiam podzielony jest na dwie czesci.</p>';
   print'<p align="justify">Jedna z nich to polkula wschodnia niezbadana od niezliczonych lat, dla zwyklych smiertelnikow nieznana i niedosiegalna. Zachowana wiedza o tym swiecie wspomina, iz znajduje sie tam legendarny Ocean Burz i niedostepny Zapomniany Kontynent. Druga polkula (zachodnia), to ogromne Ziemio-Morze podzielone na 10 ogromnych archipelagow. Niespotykana nigdzie ilosc potworow, istot, mitow i tajemnic, bogate rzeki i morza, zyzne lady, bogactwo zwierzat czyni z tego obszaru miejsce, gdzie wystepuje w praktyce wszystko, co mozna oczekiwac od mitycznego swiata fantasy.</p>';
   print'<p align="justify">W tym tez swiecie ojczyzna wszystkich "Awanturnikow" bedzie najbardziej cywilizowany, umieszczony centralnie wzgledem innych ladow obszar, zwany Archipelagiem Centralnym, a szczegolnie jego najwieksza wyspa ORKUS WIELKI.</p>';
   print'<p align="justify"><img align="right" src="obrazy/img002.jpg" />Archipelag Centralny jest polozony w polnocnej czesci polkuli zachodniej, nieco na polnoc od zwrotnika. Wokol niego lezy 8 symetrycznie rozrzuconych Archipelagow, z ktorych 3 poludniowe znajduja sie na wysokosci rownika, a 3 polnocne leza w okolicach kola podbiegunowego. Wszystkie te 9 archipelagow, niby siec lub ramiona otacza zewszad i oddziela od siebie inny Archipelag, zwany Pajeczym. Na poludnie od rownika tworzy on miniaturowy kontynent, zwany ANGCHOR (Smierci). Jest to najbardziej straszliwy, prastary, zapomniany i tajemniczy archipelag Orchii, ktory nigdy nie pozwolil siê ucywilizowac.</p>';
   print'<p align="justify">Obszar Orkusa Wielkiego i innych wysp Archipelagu Centralnego, a wiec ten na ktorym rozgrywan jest GRA ze swym klimatem porownywalny do dzisiejszego zwrotnikowo-umiarkowanego, morskiego klimatu Ziemi.</p>';
   print'<p align="justify">Podstawowa roslina pokarmowa na Orkusie jest niezmiernie bogata miedzy innymi w skrobie odmiana agawy. Ta szybko rosnaca roslina, wysoka na metr, o grubych dlugich, soczystych lisciach stanowi glowny pokarm wszelkich osiadlych ras, a przede wszystkim jest praktycznie niewyczerpalnym zrodlem paszy dla ogromnych stad bawolow - Opasow i innych roslinozercow.</p>';
   print'<p align="justify">Czasy, w ktorych najlatwiej umiejscowic GRE, zaczynaja sie od 455 roku (wedlug oficjalnie uznawanego kalendarza w tym swiecie jest to rok 95 455 TRANSSU KARTANA).</p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>MAGIA</i></b></td></tr></table></legend>';
   print'<p align="justify"><img align="left" src="obrazy/img003.jpg" />Magia na Orchii jest bardzo rozpowszechniona, jako ze swiat ten przepelniony jest energia zwana tu POTENCJALEM MAGICZNYM (w skrocie PM). Jest to blizej nie okreslona magiczna sila wystepujaca w pewnych niewielkich porcjach. Kazdy taki ladunek PM liczony jest jako 1 punkt i umozliwia rzucanie czarow.</p>';
   print'<p align="justify">Potencjal Magiczny wystepuje praktycznie we wszystkich przedmiotach lub istotach na tym planie egzystencji (aczkolwiek, jako WYJATEK, znane sa golemy absolutnie niemagiczne i odporne na niemal cala magie). Niektore istoty (np. wargi, trolle, gryfony) dzieki temu, ze ich cialo jest lekko magiczne, zyskuja wiele swej Zywotnosci i Obrony.</p>';
   print'<p align="justify">Problemem zwiazanym z Potencjalem Magicznym jest to, iz tylko nieliczni (i to po specjalnych przeszkoleniach) sa w stanie pobierac go i wykorzystywac. Drugim aspektem tej sprawy jest fakt, ze do konca nie jest on zbadany i przysparza niekiedy klopotow, szczegolnie przy nieostroznym obchodzeniu sie z nim. W oparciu o wykorzystywanie PM powstaja ogromne czary, a takze wiele dziedzin zycia nieistniejacych z reguly na innych Planach Egzystencji. Czary te w zaleznosci od osob, ktore sie w nich specjalizuja, podzielono na 8 grup. Sa to czary: kaplanskie, druidyczne, astrologiczne, polboskie, magow, czarnoksieskie, iluzjonistyczne i alchemiczne. Poniewaz w kazdej takiej grupie maja one rozna sile i poziom komplikacji, podzielono je na minimum 10 (podstawowych) KREGOW MAGII (czary najtrudniejsze, najpotezniejsze i najbardziej skomplikowane zaliczono do innych, tzw. "Specjalnych" Kregow Magii).</p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>LEGENDA</i></b></td></tr></table></legend>';
   print'<p align="justify"><img align="right" src="obrazy/img004.jpg" />ORCHIA jest planeta, ktora znajduje sie na jednym z niezliczonych Planow Materialnych (swiatow "rownoleglych" do naszego swiata rzeczywistego), a reprezentuje ona oraz wszystko co jej dotyczy Piaty Materialny Plan Egzystencji. Dla ulatwienia, swiat w ktorym my zyjemy, zaliczany jest do Pierwszego Materialnego Planu Egzystencji, swiat Hyperborejski stworzony wedlug historii losow Conana Howarda jest Drugim Materialnym Planem Egzystencji, Ziemiomorze Urszuli Le Guin jest trzecim tego typu swiatem, a calosc swiata stworzonego wedlug Tolkiena jest Czwartym Materialnym Planem Egzystencji.</p>';
   print'<p align="justify">Historie tego swiata zaczyna legenda o 13 Krysztalach Czasu. Glosi ona, ¿e Krysztaly te powstaly u zarania dziejow stworzenia Pierwszego Planu Materialnego przez dzialajace po raz pierwszy i jak na razie ostatni zgodnie, najwieksze Sily Dobra, Zla i Neutralnosci, Potegi Swiatlosci, Ciemnosci, Zywiolow i Chaosu.</p>';
   print'<p align="justify">Kazdy Krysztal skladal sie z ogromnej, przezroczystej, krysztalowej kuli, wewnatrz ktorej znajduja sie trzy Kule Mocy - Zielona dajaca zycie, Czerwona sprowadzajaca smierc i Czarna przynoszaca zapomnienie.</p>';
   print'<p align="justify">Niezliczone legendy opiewaja potege i moce, jaka posiada ich wlasciciel, lecz wszyscy sa zgodni, co do jednego: Wladca Krysztalu staje sie niesmiertelny, zachowuje swa urode i jego zyczenie jest zawsze spelniane.</p>';
   print'<p align="justify">Posiadacz Kryszta³u nie od razu staje siê jego wladca. Wpierw musi on przezyc tzw. Probe Istnienia, czyli przezwyciezyc moc Krysztalu i przetrwac przez rok wszystkie proby odebrania mu go, zwlaszcza, ze choc Krysztalu w zaden sposob nie mozna zlokalizowac, to bardzo latwo wielu poteznym istotom przychodzi odnalezienie tego, ktory np. ostatni widzial Krysztal lub cokolwiek o nim wie.</p>';
   print'<p align="justify">Artefakty te wiaza sie niestety z niezwykle wielka moca i jeszcze wieksza wladza nad przeznaczeniem. Jedna z legend glosi, ze z powodu krysztalow zostala naruszona rownowaga w wielu krainach, swiatach i planach egzystencji, a niektore z nich ulegly zagladzie lub zapomnieniu. Moc ta nie oszczedzala nawet i Bogow. Kazda Sila Zla, Dobra, Neutralnosci itp. zaangazuje wszystkie swe moce na najmniejsza oznake odnalezienia wiadomosci o miejscu ukrycia chocby Kuli Mocy. Tak na przyklad postapi kazda inteligentna, zachlanna lub ambitna istota.</p>';
   print'<p align="justify">Ostatnia z legend glosi, ze jeden z Krysztalow Czasu zostal ukryty na Orchii nalezacej do Piatego Materialnego Planu Egzystencji wiele milionow wiekow przed obecnymi czasami, na ladzie nalezacym obecnie do Archipelagu Centralnego. Najwieksza wyspa Archipelagu Centralnego jest wyspa Orkus Wielki.</p></fieldset>';
   print'<fieldset><legend><table border><tr><td><b><i>HISTORIA ORCHII</i></b></td></tr></table></legend>';
   print'<p align="justify"><img align="left" src="obrazy/img005.jpg" />Najpospolitsza humanoidalna rase Orchii stanowia orki, wraz ze swymi mieszancami (polorki), pobratymcami (gobliny, hobgobliny) i kanibalistycznymi wynaturzeniami (orkony, gobory, hobgory). Juz od niepamietnych czasow rzadzila nimi, ustanawiajac wszedzie wlasne prawo i cywilizacje arystokratyczna podrasa Uruk-hai. Ich dziesiec jak dotad nie wygaslych dynastii roslo w taka sile i moc, az jeden z nich o imieniu Kartan zostal najmlodszym i jednym z najpotezniejszych Bogow Orchii, przyjmujac imie KATAN. Odtad wszyscy wladcy wspomnianych dynastii (z ktorych kazda rzadzi innym Archipelagiem) uwazaja sie za jego potomkow i zarazem wcielenia, przyjmujac to imie. Szerzac wiare w niego i samych siebie, kazdy z nich staje sie poteznym Polbogiem, a moc Wielkiego Katana zawsze im sprzyja.</p>';
   print'<p align="justify">Mimo ogromnej ilosci najrozniejszych ras, orkom pod wodza swych Katanow udalo sie podporzadkowac je i ustanowic sprawiedliwe, choc srogie rzady. Kazda rasa posiada rowny zakres wolnosci i praw, aczkolwiek musi sie podporzadkowac woli (w praktyce nienaduzywanej) i zwierzchnictwu rzadzacej dynastii. Lagodne, sprawiedliwe i czesto opiekuncze traktowanie obcych ras w zamian za oficjalne uznawanie wladzy Katanow po wielu wojnach doprowadzilo do powstania wielorasowej, z reguly pozbawionej antagonizmow cywilizacji o w miare spojnej spolecznosci.</p>';
   print'<p align="justify">Kazdy Katan rzadzi innym archipelagiem i poza Pajeczym sprawuje tam faktyczna wladze. W utrzymaniu posluszenstwa pomaga mu fakt, ze swiat ten zamieszkuje niezliczona liczba istot niebezpiecznych, przez co stacjonujace w prawie kazdym miescie garnizony orkow spelniaja pozyteczna prace i sa za to wysoko cenione przez wszelkie miejscowe nacje. Ponadto, dzieki nie mieszaniu sie w wewnetrzne sprawy miejscowych wladcow i nie narzucaniu im bez waznego powodu swej woli, Katanowie czesto sa sedziami i rozjemcami. I chociaz gdy potrzeba, ze swym charakterem, sa niezwykle okrutni i bezlitosni, to doskonale zdaja sobie sprawe, ze ich wladza trwa dlugo tylko dzieki jej pozytecznosci i nienaduzywaniu jej.</p>';
   print'<p align="justify">Nie zawsze jednak orki panowaly na Orchii. Kiedys ich role pelnilo potezne spoleczenstwo reptillionow. Dzieje upadku swietnosci tej rasy siegaja czasow Wielkiego Kartana, wodza i zjednoczyciela wszystkich orkow, ktory za swych rzadow stoczyl jedna z najkrwawszych wojen wlasnie z reptillionami. Po wielkich bitwach szala zwyciestwa stanowczo przechylila sie na strone reptillionow. By odmienic losy przeznaczenia Kartan zawarl pokoj ze wszystkimi reptillionami, wierzacymi w ich naczelnego boga (Reptilliona Wielkiego) i jako symbol ugody ofiarowal im wszystkie podziemne wlosci, ktore do tej pory zamieszkiwaly orki i ich pobratymcy oraz zawarl z nimi wieczysty pokoj. Gdy sludzy Reptilliona Wielkiego objeli juz na dobre swe nowe dziedzictwo, pomagajac wczesniej usunac ich dawnych mieszkancow, Kartan najechal wraz z wypedzonymi pozostalych reptillionow, odnoszac wielkie i wyjatkowo krwawe zwyciestwo. Odtad rasa ta na zawsze zwiazala sie z dawnymi siedzibami (jaskiniami) orkow, a zwycieski wodz hordy bezdomnych i nie majacych co zrobic ze soba orkow osiedlil ich i ucywilizowal, przez co stworzyl prezna cywilizacje istniejaca do dzis.</p></fieldset>';
?>


